name: CI/CD

on:
  push:
    branches: [ main, feature/arrayBuffer ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 设置 Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: 安装依赖
      run: npm i

    - name: 构建项目
      run: npm run build

    - name: 压缩构建文件
      run: tar -czf build.tar.gz dist

    - name: 上传构建文件
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: build.tar.gz

  deploy:
    needs: build
    environment: dr
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: 下载构建文件
      uses: actions/download-artifact@v4
      with:
        name: build-artifact

    - name: 部署到服务器
      uses: appleboy/scp-action@master
      with:
        host: ${{ vars.HOST }}
        username: ${{ vars.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "build.tar.gz"
        target: "/home/restry/langflow-runtime/caddy/site"

    - name: 解压文件并重启服务
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.HOST }}
        username: ${{ vars.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/restry/langflow-runtime/caddy/site
          mkdir -p pdfpreview
          tar -xzf build.tar.gz -C pdfpreview --strip-components=1
          rm build.tar.gz
